coverage:
  status:
    project:
      default:
        target: auto
        threshold: 90%
        base: auto
    patch:
      default:
        target: auto
        threshold: 80%
        base: auto

ignore:
  - "examples/"
