repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check_added_large_files
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: trailing-whitespace
      - id: detect-private-key
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black .
        language: python
      - id: pylint
        name: pylint
        entry: pylint mpopt
        language: python
        types: [ python ]
        args: [ --in-place, --remove-all-unused-imports, --remove-duplicate-keys ]
        pass_filenames: false
