name: actions

on:
  push:
    branches: [ Alex_path ]
  pull_request:
    branches: [ Alex_path ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2

      - name: Set up Python 3.9 
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Set up Poetry
        run: pip install poetry 
      
      - name: Install dependencies
        run: poetry install
      
      - name: Generate report
        run: |
          poetry run coverage run -m pytest tests
          poetry run coverage report

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
          files: /home/runner/work/MPOpt/MPOpt/.coverage
          verbose: false
        
  lint:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2

      - name: Set up Python 3.9 
        uses: actions/setup-python@v2
        with:
         python-version: 3.9

      - name: Set up Poetry
        run: pip install poetry 
      
      - name: Install dependencies
        run: poetry install
        
      - name: Run linter
        run: poetry run pylint mpopt --fail-under=8
        
