name: actions

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2

      - name: Set up Python 3.9 
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Set up Poetry
        run: pip install poetry 
      
      - name: Install dependencies
        run: poetry install
      
      - name: Generate report
        run: |
          pip install coverage
          pip install pytest
          coverage run -m pytest tests
          coverage report

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true
          token: fb9057ec-90fc-4902-9965-3ebb4d81d4f5
        
  lint:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2

      - name: Set up Python 3.9 
        uses: actions/setup-python@v2
        with:
         python-version: 3.9

      - name: Set up Poetry
        run: pip install poetry 
      
      - name: Install dependencies
        run: poetry install
        
      - name: Run linter
        run: poetry run pylint mpopt --fail-under=8
        
